// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSIY2s4qRsGAy3aAP-LtB4vjyXTJLdmE',
    appId: '1:2731628059:web:8b156127ff9d0109170abe',
    messagingSenderId: '2731628059',
    projectId: 'midterm-indagram',
    authDomain: 'midterm-indagram.firebaseapp.com',
    storageBucket: 'midterm-indagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0x_JIt212YvBt9tACGPl5n_LYXHvx0s',
    appId: '1:2731628059:android:4ad9e9414b0e8673170abe',
    messagingSenderId: '2731628059',
    projectId: 'midterm-indagram',
    storageBucket: 'midterm-indagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABd66G5moHSd-sYwZI8VSaxEkF1C5qDzg',
    appId: '1:2731628059:ios:b2590eabbb9da707170abe',
    messagingSenderId: '2731628059',
    projectId: 'midterm-indagram',
    storageBucket: 'midterm-indagram.appspot.com',
    iosClientId: '2731628059-pls9co13dh06cfvsj14mkl1gbt339pt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram1',
  );
}
